AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 instances and ALB for Project 1 - Outline of Resources/Parameters

# Need to ask user for name of network stack
Parameters:
  NetworkStackName:
    Type: String
    Description: Name of the Cloud Formation Template 1 - Network Stack
    Default: Project1Network
Resources:

  # Optional BastionHostInstance would go here

  WebServerInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-015f56077b7f5b83f"
      InstanceType: t2.micro
      KeyName: "project1"
      SubnetId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PvtSub1"
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-WebServSG"
  WebServerInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-015f56077b7f5b83f"
      InstanceType: t2.micro
      KeyName: "project1"
      SubnetId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PvtSub2"
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-WebServSG"
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: 
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VPCID"
      HealthyThresholdCount: 2
      Name: Project1ALBTargetGroup
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !Ref  WebServerInstance1
          Port: 80
        - Id: !Ref WebServerInstance2
          Port: 80
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Name: Proj1LoadBalancer
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-ALBSG"
      Subnets:
      - Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-PubSub1"
      - Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-PubSub2"
Outputs:
  ApplicationLoadBalancer:
    Description: URL of the Loadbalancer
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - ApplicationLoadBalancer
          - DNSName